# Generated by Django 6.0.5 on 2026-06-19 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('SULOM_ADMIN', 'SULOM Administrator'), ('CLUB_ADMIN', 'Club Administrator'), ('TICKET_OFFICER', 'Ticket Officer'), ('SUPPORTER', 'Supporter')], max_length=32)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfetms_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
