# Generated by Django 6.0.5 on 2026-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('short_name', models.CharField(max_length=40)),
                ('organization_type', models.CharField(choices=[('FAM', 'Football Association of Malawi'), ('SULOM', 'Super League of Malawi'), ('REGIONAL_ASSOCIATION', 'Regional Association'), ('CLUB', 'Club')], max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('logo', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
