# Generated by Django 6.0.5 on 2026-06-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=80)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('coach', models.CharField(blank=True, max_length=120)),
                ('logo', models.URLField(blank=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='organizations.organization')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stadiums.stadium')),
            ],
        ),
    ]
