# Generated by Django 6.0.5 on 2026-06-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider', models.CharField(choices=[('TNM_MPAMBA', 'TNM Mpamba'), ('AIRTEL_MONEY', 'Airtel Money'), ('NBS_BANK', 'NBS Bank'), ('FDH_BANK', 'FDH Bank'), ('NBM_BANK', 'National Bank of Malawi')], max_length=32)),
                ('transaction_reference', models.CharField(max_length=80, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tickets.ticket')),
            ],
        ),
    ]
