# Generated by Django 6.0.5 on 2026-06-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('season', models.CharField(max_length=20)),
                ('competition_type', models.CharField(choices=[('LEAGUE', 'League'), ('CUP', 'Cup'), ('WOMENS_LEAGUE', "Women's League"), ('DIVISION', 'Division')], max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to='organizations.organization')),
            ],
            options={
                'unique_together': {('name', 'season')},
            },
        ),
    ]
