# Generated by Django 6.0.5 on 2026-06-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueShareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default gate collection sharing', max_length=120)),
                ('fam_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('sulom_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('home_team_percentage', models.DecimalField(decimal_places=2, default=45, max_digits=5)),
                ('away_team_percentage', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('stadium_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('security_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fam_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sulom_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('home_team_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('away_team_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stadium_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('security_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('distribution_date', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_distribution', to='matches.match')),
            ],
        ),
    ]
